services:
  postgres:
    image: postgres:17-alpine
    container_name: webapp-nail-postgres-dev
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - webapp_nail_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  webapp_nail_postgres_data:
